### PR TITLE
Enable compiler optimizations

### LINKED ISSUE #1: Run/compile macros with optimizations
I just learned [from this post](https://root-forum.cern.ch/t/scalability-of-rdataframes-on-16-cores/44222/48) that loading macros with `.L` the way we currently do runs them as unoptimized code, i.e., it JIT-compiles them with `-O0`. We should investigate how to compile the macros with optimizations instead and consider using that for our measurements.

### PR DESCRIPTION
**Pull request by masonproffitt**
Resolves #1.

### CODE REVIEW

**Comment by ingomueller-net** [comment]
@masonproffitt: Unfortunately, it does not seem that simple. When I run the benchmarks on this commit, I get the following error:

```
docker run --rm -it opendata-benchmarks:optimized run_benchmark.sh -n 1 1
Info in <TUnixSystem::ACLiC>: creating shared library /root/util/././../macros/benchmark1_C.so
In file included from input_line_12:6:
./././../macros/benchmark1.C:3:31: error: no member named 'EnableImplicitMT' in namespace 'ROOT'
    if (multithreading) ROOT::EnableImplicitMT();
                        ~~~~~~^
./././../macros/benchmark1.C:5:11: error: no member named 'RDataFrame' in namespace 'ROOT'
    ROOT::RDataFrame df("Events", input);
    ~~~~~~^
./././../macros/benchmark1.C:6:14: error: use of undeclared identifier 'df'
    auto h = df.Histo1D({"", ";MET (GeV);N_{Events}", 100, 0, 2000}, "MET_pt");
             ^
./././../macros/benchmark1.C:8:5: error: unknown type name 'TCanvas'
    TCanvas c;
    ^
Error in <ACLiC>: Executing '/opt/root/bin/rootcling -v0 "--lib-list-prefix=/root/util/././../macros/benchmark1_C_ACLiC_map" -f "/root/util/././../macros/benchmark1_C_ACLiC_dict.cxx" -I$ROOTSYS/include -I"/opt/root/etc/" -I"/opt/root/etc//cling" -I"/opt/root/include/" -I"/opt/root/include" -D__ACLIC__  "/root/util/././../macros/benchmark1.C" "/root/util/././../macros/benchmark1_C_ACLiC_linkdef.h"' failed!
input_line_12:2:3: error: use of undeclared identifier 'benchmark1'
 (benchmark1())
  ^
```

I was able to fix the compilation errors (by including some of the headers from the macros that the "official" implementation also includes), but then ran into linking errors, which I have no idea how to fix.

**Comment by masonproffitt** [comment]
Yeah, I went through the same process. The `+` compiles a shared library in the directory of the macro rather than the working directory, so the linker doesn't see it. I got it to work by setting `LD_LIBRARY_PATH`, though. I'll add these to the PR when I get a chance.

**Comment by masonproffitt** [comment]
Actually I think it works (i.e. produces the right output files) even with the linking errors (so I'm not exactly sure what it's doing in that linking step), but I guess it's best to avoid them.

**Comment by ingomueller-net** [comment]
Awesome! I just tried this out; unfortunately, [without any significant improvements](https://root-forum.cern.ch/t/scalability-of-rdataframes-on-16-cores/44222/56).

**Pull request merged**
